name: Code Quality Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: CI Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24
      - name: Configure JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "temurin"
          java-version: "25"
      - uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        name: Yarn Cache Restore
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-v1
      - name: Yarn Install
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3
        with:
          timeout_minutes: 15
          retry_wait_seconds: 30
          max_attempts: 3
          command: yarn
      - name: Lint
        run: ./test.sh
      - uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        name: Yarn Cache Save
        if: "${{ github.ref == 'refs/heads/main' }}"
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
